name: Build Rootfs

on:
  push:
    tags:
      - '*'

jobs:
  build-docker-find-ubuntu:
    name: Build ubuntu docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        tags: anyfiddle/find-ubuntu:latest
        push: true

  build-ubuntu-docker-rootfs:
    name: Build ubuntu docker rootfs
    needs: [build-docker-find-ubuntu]
    runs-on: ubuntu-latest
    container: 
      image: anyfiddle/firecracker-rootfs-builder:latest
      options: "--entrypoint /bin/sh --privileged"
    steps:
    - uses: actions/checkout@v2
    - name: Build docker root fs
      shell: sh
      run: |
        cd /workspace
        ls
        ./create-rootfs.sh anyfiddle/find-ubuntu:latest
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Uploading latest image
      env:
        TAG_REF: ${{ github.ref }}
      run: |
        gsutil cp /output/image.ext4 gs://anyfiddle-find/rootfs/ubuntu-image-latest.ext4