name: Build Rootfs

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-docker-find-ubuntu:
    name: Build ubuntu docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        tags: anyfiddle/find-ubuntu:latest
        push: true

  build-ubuntu-docker-rootfs:
    name: Build ubuntu docker rootfs
    needs: [build-docker-find-ubuntu]
    runs-on: ubuntu-latest
    container: 
      image: anyfiddle/firecracker-rootfs-builder:latest
      options: "--entrypoint /bin/sh"
    steps:
    - uses: actions/checkout@v2
    - name: Buidl docker root fs
      shell: sh
      run: |
        cd /workspace
        ls
        ./create-rootfs.sh anyfiddle/find-ubuntu:latest
