name: Build Rootfs

on:
  push:
    tags:
      - '*'

jobs:
  build-docker-find-ubuntu:
    name: Build ubuntu docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        tags: anyfiddle/find-ubuntu:latest
        push: true

  build-ubuntu-docker-rootfs:
    name: Build ubuntu docker rootfs
    needs: [build-docker-find-ubuntu]
    runs-on: ubuntu-latest
    container: 
      image: anyfiddle/firecracker-rootfs-builder:latest
      options: "--entrypoint /bin/sh --privileged"
    steps:
    - uses: actions/checkout@v2
    - name: Build docker root fs
      shell: sh
      run: |
        cd /workspace
        ls
        ./create-rootfs.sh anyfiddle/find-ubuntu:latest
    - name: Create Release for tag
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /output/image.ext4
        asset_name: image.ext4
        asset_content_type: application/octet-stream
